import Button from "@/components/Button/Button";
import HomepagePopup from "@/components/HomepagePopup/HomepagePopup";
import Header from "@/modules/Header/Header";

import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [isDisplayed, setIsDisplayed] = useState(false);

  useEffect(() => {
    const isDisplayedToken = localStorage.getItem("displayToken") === null;
    setIsDisplayed(isDisplayedToken);
  }, []);

  return (
    <>
      <Head>
        <title>My News App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isDisplayed && <HomepagePopup isDisplayed={isDisplayed} setIsDisplayed={setIsDisplayed} />}
      <Header />
    </>
  );
}
