import Head from "next/head";
import { SyntheticEvent, useEffect, useRef, useState } from "react";
import HomepagePopup from "@/components/HomepagePopup/HomepagePopup";
import Header from "@/modules/Header/Header";
import Section from "@/components/Section/Section";
import NavBar from "@/modules/NavBar/NavBar";
import Grid from "@/components/Grid/Grid";
import LatestNews from "@/modules/LatestNews/LatestNews";
import Article from "@/components/Article/Article";
import { fetchNewsData } from "@/redux/actions/fetchNewsDataAction";
import { useAppDispatch, useAppSelector } from "@/utility/hooks";
import ToggleNews from "@/modules/ToggleNews/ToggleNews";
import { NewsItem } from "@/redux/reducer/fetchNewsDataReducer";
import styles from "../Home.module.scss";

export default function Home() {
  const [isDisplayed, setIsDisplayed] = useState<boolean>(false);
  const [showLatestNews, setShowLatestNews] = useState<boolean>(false);
  const [data, setData] = useState<NewsItem[]>([]);
  const shouldDispatch = useRef<boolean>(true);

  const dispatch = useAppDispatch();
  const { newsData } = useAppSelector(state => state.news);

  useEffect(() => {
    if (shouldDispatch.current) {
      dispatch(
        fetchNewsData({ section: "sports", limit: 10, offset: newsData.length })
      );
      shouldDispatch.current = false;
    }
  }, []);

  useEffect(() => {
    setData(
      newsData
        .slice()
        .sort(
          (a, b) =>
            new Date(b.publishedDate).getTime() -
            new Date(a.publishedDate).getTime()
        )
    );
  }, [newsData]);

  useEffect(() => {
    const isDisplayedToken = localStorage.getItem("displayToken") === null;
    setIsDisplayed(isDisplayedToken);
  }, []);

  const handleSearch = (e: SyntheticEvent<HTMLInputElement>) => {
    setData(
      newsData.filter(news =>
        news.title.toLowerCase().includes(e.currentTarget.value.toLowerCase())
      )
    );
  };

  return (
    <>
      <Head>
        <title>My News App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isDisplayed && <HomepagePopup setIsDisplayed={setIsDisplayed} />}
      <Header handleSearch={handleSearch} />
      <main className={styles["Home"]}>
        <div className={styles["Home-ToggleNews"]}>
          <ToggleNews setShowLatestNews={setShowLatestNews} />
        </div>
        <Section>
          <div className={styles["Home-NavBar"]}>
            <NavBar />
          </div>
          <Grid title={"News"}>
            <div className={styles["Home-LatestNews"]}>
              <LatestNews />
            </div>
            {showLatestNews ? (
              <div className={styles["Home-LatestNews_mobile"]}>
                <LatestNews />
              </div>
            ) : (
              data
                .filter(item => item.section.toLocaleLowerCase() === "sports")
                .map(
                  ({
                    section,
                    title,
                    imageCaption,
                    imageUrl,
                    author,
                    isFavourite,
                    id,
                  }) => (
                    <Article
                      key={id}
                      title={title}
                      section={section}
                      imageCaption={imageCaption}
                      imageUrl={imageUrl}
                      author={author}
                      isFavourite={isFavourite}
                      id={id}
                    />
                  )
                )
            )}
          </Grid>
        </Section>
      </main>
    </>
  );
}
